sudo: required

language: csharp

cache:
  directories:
    - packages

services:
  - docker

before_install:
  - docker build -t webapp:test -f ./Docker/Dockerfile .

script:
  - docker run -it --rm -v $PWD/packages:/root/.nuget/packages webapp:test